spring:
  redis:
    data:
      host: localhost
      port: 6379
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/padakdev
    username: admin
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 9902
